### ISSUE TITLE
Question on ECS SB

### ISSUE THREAD

**Issue by MaheshRudrachar** [emccode/ecs-cf-service-broker#50]
Hi,

Quick questions to validate my POC:

1. Which version of ECS is supported by this Service Broker? Is this service broker works for both public and on-premise version of ECS?
2. Basic Authentication is still supported? I could see in EMC API documentation it says Authorization SigV2 for encryption?
3. Regarding Ports: 
     Public ECS solution supports only 443, 9020 ad 9021 ports is for On-premise ECS Solution?

I tried running this service broker on CF, but resulting with 400 error during Login->jerseyClient.target(uriBuilder).request().get(). I am suspecting the support of https://baseurl:9021/login

Your inputs are very much appreciated. 

Thanks
MR

**Comment by spiegela** [comment]
Mahesh:

Thanks for reaching out!  Here are some answers:

>  1  Which version of ECS is supported by this Service Broker? Is this service broker works for both public and on-premise version of ECS?

The broker works against the ECS management API for creating service instances (today only buckets, but soon also namespaces) and bindings (user accounts with credentials to a bucket).  This means that it can work with either private or public ECS clusters (including [community edition](https://github.com/EMCECS/ECS-CommunityEdition)), so long as you have management credentials to a namespace on the cluster.  In the case of [ECSTestdrive](https://portal.ecstestdrive.com), the broker doesn't work (yet) since the management API (port 4443) is not exposed.

>  2  Basic Authentication is still supported? I could see in EMC API documentation it says Authorization SigV2 for encryption?

The credentials handed out are for an object user, and the expectation is to use ports 9020 or 9021 to address the S3 API.  ECS currently supports the AWS S3Signer for authentication, but work is in progress to support in ECS to AWS v4 HMAC authorization, which is the new default.

>  3  Regarding Ports: Public ECS solution supports only 443, 9020 and 9021 ports is for On-premise ECS Solution?

Port 443 is used (by default) for the ECS UI, not the S3 API.  Ports 9020 and 9021 should both be exposed for a public or private ECS cluster; however, if a different port is used (for example, if a load balancer is directing traffic to 9021 over port 443), then the `broker.object-endpoint` parameter can be configured via the `application.properties` file or using the `BROKER_OBJECT_ENDPOINT` environment variable.

>  tried running this service broker on CF, but resulting with 400 error during Login-> jerseyClient.target(uriBuilder).request().get(). I am suspecting the support of https://baseurl:9021/login

Here, it looks as if you are using the login method for the ECS management API (which is typically exposed via port 4443) against the S3 port (9021).  AWS S3 uses a header based signed authorization field, and doesn't expose a `/login` endpoint, which is why you're getting a 400 error.

For a Java application, you might consider using [Spring Cloud Connectors](http://cloud.spring.io/spring-cloud-connectors/).  You don't have to use all of Spring Framework to get these, and they will wire up the environment variables to your bucket services easily.

I have [sample project](https://github.com/spiegela/ecs-scc-demo/tree/custom-connector) that just just that.  The [connector](https://github.com/spiegela/ecs-scc-demo/tree/custom-connector/src/main/java/com/emc/ecs/connector) in the project provides a [AWS-S3 SDK client](https://aws.amazon.com/sdk-for-java/) with the authentication parameters already setup properly.

Here's a snippet from the ["connection creator" class](https://github.com/spiegela/ecs-scc-demo/blob/custom-connector/src/main/java/com/emc/ecs/connector/spring/S3ServiceConnectorCreator.java) that shows how this is done:

```java
ClientConfiguration clientConfig = new ClientConfiguration();
clientConfig.setSignerOverride("S3SignerType");
S3ClientOptions options = S3ClientOptions.builder().setPathStyleAccess(true).build();
AWSCredentials awsCredentials = new BasicAWSCredentials(
  // credentials are provided by a config service here:
  serviceInfo.getAwsAccessKey(), serviceInfo.getAwsSecretKey());
AmazonS3 amazonS3 = new AmazonS3Client(awsCredentials, clientConfig);
amazonS3.setEndpoint(serviceInfo.getEndpoint());
amazonS3.setS3ClientOptions(options);
// now your S3 client is ready to use with ECS 2.2
```

Feel free to continue to comment on this issue if you have more questions, or if some of this doesn't make sense.  I'll be drafting a blog post based on my recent EMCWorld presentation that shows the setup process in more detail, so it _very_ helpful for me to know which parts are confusing -- we'll either improve the documentation or the code to make this easier ;-)

**Comment by MaheshRudrachar** [comment]
@spiegela 👍 
Thanks for your detailed explanation, time and references...

**Comment by spiegela** [comment]
@MaheshRudrachar I'll leave the issue open for a bit, just in case you have any follow up questions.  If you would, let me know when you'd like me to close.

**Comment by MaheshRudrachar** [comment]
Sure..

Here is set of few more questions to you :)

1. User authentication token (X-SDS-AUTH-TOKEN) is meant only for Management APIs right? Is it still valid in the broker code? And Object endpoint S3 APIs follows AWS SigV2 as shown in the snippet

2. Could you explain the usage of CF Metadata Bucket that gets automatically created at startup

3. Is there a limitation in the number of users/secretkeys that are generated for a given bucket?

4. Support for High availability in case of On-premise solution?

5. Billing model, if that can disclosed?

6. Usecases that ECS could address compared to other solutions?

7. Can ECS be mounted to containers/dockers as compared to using it just as an object browser?

8. Backup and Restore of Bucket data supported?

**Comment by spiegela** [comment]
> 1 User authentication token (X-SDS-AUTH-TOKEN) is meant only for Management APIs right?

Correct.

> Is it still valid in the broker code? And Object endpoint S3 APIs follows AWS SigV2 as shown in the snippet

The broker really only hands out S3 credentials right now, which are used like in the snippet.  We could expose additional bucket types and credentials (ECS management, swift, atoms, etc.)  These additional APIs could be exposed as additional services in the catalog, if that's valuable.

> 2 Could you explain the usage of CF Metadata Bucket that gets automatically created at startup

CF service brokers _must_ have a way to persist the service-instance and binding metadata generated from `create-service` and `bind-service` requests.  Many brokers will store this info in a database, but we chose to use a bucket to store the data since it's already there.

> 3 Is there a limitation in the number of users/secretkeys that are generated for a given bucket?

There are no limits imposed by the broker.  I don't think there are user-count limits in ECS, but I'll check.

> 4 Support for High availability in case of On-premise solution?

Yes, buckets can be part of an ECS replication-group with multiple sites -- anywhere from 1 to 8 sites. Currently a single broker supports a single namespace and replication-group, but you can run multiple brokers.  Soon we'll support multiple namespaces & replication-groups.

> 5 Billing model, if that can disclosed?

If you're asking about exposing billing info from the broker, then catalog plans can expose multiple different billing options, and metering can be done via the ECS management API.  The broker itself doesn't implement them this kind of monitoring.

If you're asking has ECS itself is licensed, it can be sold as an appliance or as software (per TB license).  It's also available through a number of public cloud service providers.  You can work with your EMC account team or the [EMC store](https://store.emc.com/us/Product-Family/EMC-Elastic-Cloud-Storage-Products/EMC-Elastic-Cloud-Storage/p/EMC-Elastic-Cloud-Storage-ECS-Appliance) to learn more.

> 6 Use cases that ECS could address compared to other solutions?

Oh, that's a longer conversation.  I recommend engaging your EMC software-defined account team.  Short answer-- there are a bunch:  erasure coding and good performance for objects of all sizes, flexible multi-site configs, transparent access across HDFS/Object/NAS protocols, and more.

> 7 Can ECS be mounted to containers/dockers as compared to using it just as an object browser?

You can definitely address ECS within a container either using Docker volumes & NFS, or (probably better) just addressing it via S3/Swift/etc in the Dockerized app.

> 8 Backup and Restore of Bucket data supported?

ECS supports bucket versioning and multi-site replication.  Object/bucket restores can be performed via the object APIs  that support versioning (like S3).  These feature typically mean that ECS itself doesn't need to be backed up, but it certainly could be via NFS or a script.

**Comment by MaheshRudrachar** [comment]
Thanks a bunch.... @spiegela 

When will this feature will be supported in service broker - "support multiple Cloud Foundry instances"?
Pivotal suggest to use different base urls with unique id like broker.example.com/123, broker.example.com/456 etc... really didn't get how to proceed.

Do you have any thoughts as to how to implement it and any approaches. I am planning to include this in my POC...

**Comment by MaheshRudrachar** [comment]
May be after this response, you could close this.... Thanks @spiegela

**Comment by spiegela** [comment]
@MaheshRudrachar The broker supports multiple Cloud Foundry instances today.  [This article](http://docs.cloudfoundry.org/services/supporting-multiple-cf-instances.html) states that unique routes are only needed _"for the broker to know which Cloud Foundry instance"_.  Since we do not yet support a [Dashboard Single Sign-on](http://docs.cloudfoundry.org/services/dashboard-sso.html), we don't need to add these routes.

That said, when we're ready to support a dashboard SSO, we would look to extend the [Spring Cloud CF Service Broker project](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker).  This should just add a piece of metadata to each instance-creation & binding request.

**Comment by discoverkr77** [comment]
@spiegela - I had a related question. How do we make a service instance created by one CF instance available for binding in another CF instance? I think we can do that using service binding in the first instance and copying over the credentials into an user-provided service in the second instance. Do you know of a better way to do this? 

It would be nice to have service binding possible across CF Instances. I know this is a CF limitation but wondering if you have any ideas of accomplishing this outside of user-provided services.

**Comment by spiegela** [comment]
@discoverkr77 I know exactly what you mean.  You're correct that CF doesn't currently support shared services across Cloud Foundry clouds -- I'm hopeful to start some conversations about this next week :smile:.

In the meantime, a [user provided service](http://docs.cloudfoundry.org/devguide/services/user-provided.html) or manually updating a config file seem like the only effective routes.  Once issue #38 is completed, you'll be able to create _"non-binding"_ user permissions, which will ease that process greatly.
